### ISSUE TITLE
Crash on Android 13 (PIXEL EXPERIENCE)

### ISSUE THREAD

**Issue by Richard38907** [Mahmud0808/Iconify#459]
### Describe the bug

When I restart System UI. I stay stuck on Lockscreen with a System UI crash loop since the v6.7.5.

### Steps to reproduce

1. Install the update 6.7.5
2. Reboot the phone
3. Unlock the phone
4. Restart system UI
6. See crash

### Expected behavior

Instead of restarting system UI once, it start in a loop.

### Device information

- Device: [OnePlus Nord Avicii]
- OS: [PixelExperience 13 / patch september 2023]
- App version:  v6.7.5
- Magisk Magisk Delta 27.0

**Comment by Richard38907** [comment]
Disabling the module fixes the problem

**Comment by Richard38907** [comment]
Even if I do a clean install of iconify, the problem still be there. So I downgraded to v 6.7.0 to solve it.

**Comment by Mahmud0808** [comment]
Include lsposed logs

**Comment by Mahmud0808** [comment]
Fixed 69a6e58477585110510342ce5970d1700359d2dc

**Comment by Richard38907** [comment]
I updated to the 6.7.6 and the problem is still present on my system. I don't use Lsposed. Just flashing iconify causes this problem.

**Comment by Richard38907** [comment]
I cannot provide you a bug report sadly.

**Comment by Mahmud0808** [comment]
Can't help without logs. And also make sure to enable root access for both iconify and systemui from magisk delta. And disable unmount modules option too.

**Comment by Richard38907** [comment]
It's already enabled.![Screenshot_20240406-104000_Magisk.png](https://github.com/Mahmud0808/Iconify/assets/148692265/af80c4ea-78e2-45a5-9eac-42cc8e542367)

**Comment by Mahmud0808** [comment]
I can't know what's going on without logs. Re-open the issue when you have proper logs.
