### ISSUE TITLE
[BUG] A15 December new android toast design? - toast theme has "wrong" text colour now

### ISSUE THREAD

**Issue by cozykitten** [Mahmud0808/Iconify#698]
### Describe the bug

since updating to december OTA (A15) it seems like the default toast of android was changed?
I believe it was white text on dark background before on dark theme.
For some reason it now is dark text on white background, in dark mode.
So applying a translucent toast style will look off, as it doesn't (and never had to) modify the text colour.

### Steps to reproduce

apply translucent toast style with dark mode enabled.

### Expected behavior

Honestly this is expected,.. just something Android changed.
But it would be nice if the text colour would adapt (or be manually switchable) so that it is still a white text colour when dark mode is on.
Especially on the translucent styles such as style 7 (lighty).

### Screenshots

![Screenshot_20241208-152930](https://github.com/user-attachments/assets/614e1e10-9c82-4214-a089-9522015170d7)

### Device information

- Device: Pixel 6a
- OS: A15, OTA Dec
- App version: latest (6.9.0)
- Magisk/KernelSU: Magisk 28100

**Comment by Mahmud0808** [comment]
Can you show the default style of android? In both dark and light mode.

**Comment by cozykitten** [comment]
> Can you show the default style of android? In both dark and light mode.

It looks like this in both light and dark mode.
(Iconify "disable everything", disabled magisk module, rebooted)

At this point I'm wondering whether that might be a bug in android itself, given that it's the same in light and dark mode.

![Screenshot_20241209-170340.png](https://github.com/user-attachments/assets/33ba5ca1-c8e9-481f-a493-f4321d47ef6c)

![Screenshot_20241209-171027.png](https://github.com/user-attachments/assets/18a0d719-f233-4b15-9d9b-e57781265cf4)

![Screenshot_20241209-171116.png](https://github.com/user-attachments/assets/3f91f150-8816-43ac-83d6-c94bbd62168c)

**Comment by Mahmud0808** [comment]
This might be a bug from android. So will have to wait and see.

**Comment by kekkodance** [comment]
For me it only applies the edge pattern but in AMOLED mode the toast stays white. Latest commit build, reinstalled iconify with rebuilt module.

**Comment by Strange-IPmart** [comment]
> For me it only applies the edge pattern but in AMOLED mode the toast stays white. Latest commit build, reinstalled iconify with rebuilt module.

Same.
Latest december android 15 build (The November build was working fine).
Latest iconify debug.
Toast stays white with Amoled mode.

**Comment by Mahmud0808** [comment]
Fixed in debug build.

**Comment by Strange-IPmart** [comment]
The bug is still there.
Whatever style you choose, it looks like in the screenshot.
It should be black/semitransparent with accent frame and white text.

Pixel 8 Pro
Android 15 (December build)
Latest Debug

![Image](https://github.com/user-attachments/assets/9f807da0-7b42-4ad6-884f-977d6cea5c59)

**Comment by kekkodance** [comment]
still happens!! @Mahmud0808

**Comment by Mahmud0808** [comment]
@Strange-IPmart You are wrong, google made it white in both light and dark theme. So I followed that too so that texts are properly visible. Which now is, that means it has been fixed.

@kekkodance Show screenshot in both light and dark mode.
